## NumPy
- NumPy stands for Numerical Python
- Core library for numeric & scientific computing
- Consists of:
    - Multi-dimensional array objects &
    - Collection of routines for processing these arrays

In [1]:
## TO INSTALL => pip install numpy

#IMPORTING NUMPY with alias => np
import numpy as np

## Arrays

In [2]:
#SINGLE-DIMENSIONAL ARRAY
n1 = np.array([10,20,40,50])
#MULTI-DIMENSIONAL ARRAY
n2 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [4]:
##TYPE
print(type(n1))
print(type(n2))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [11]:
print("1D Array:\n",n1)
print("==============")
print("nD Array:\n",n2)

1D Array:
 [10 20 40 50]
nD Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


## Numpy Arras with zeros

In [15]:
# PROVIDE (rows,columns) in np.zeros() to get array with zeros

# 1x2 array with zeros
zeros_1x1 = np.zeros((1,2))

# 6x6 array with zeros
zero_6x6 = np.zeros((6,6))

In [16]:
print(zeros_1x1)

[[0. 0.]]


In [17]:
print(zero_6x6)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


## Array with a fixed value in every row & col

In [18]:
## CREATE 6x6 array where every element will be 7

array_with7 = np.full((6,6),7)
print(array_with7)

[[7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]]


## Array with a range

In [19]:
## IT WILL GIVE RANGE OF VALUES FROM 0-10
array_with_range = np.arange(1,11)
print(array_with_range)

[ 1  2  3  4  5  6  7  8  9 10]


In [21]:
## CREATE ARRAY FROM A RANGE OF 100 to 300 with skip value of 50
## Skip value=50 means that get every value after 50th value
## Like 100 150 200 250
new_array = np.arange(100,300,50)
print(new_array)

[100 150 200 250]


## Array with Random Numbers

In [22]:
## FOR RANDOM INTEGERS => np.random.randint(start,end,num_count)
## If I want 10 values between 100 & 200, we can do it as
rand_array = np.random.randint(100,200,10)
print(rand_array )

[117 159 167 106 153 182 187 122 166 109]


## Check shape of numpy array
- array.shape returns (col,rows)

In [23]:
rand_array.shape

(10,)

In [24]:
zeros_1x1.shape

(1, 2)

In [25]:
# We can also change shape
my_array = np.array([
    [1,2,3,7],
    [4,5,6,8]
])
print(my_array.shape)

(2, 4)


In [27]:
# Let's reshape it into 4x2 array
my_array.shape = (4,2)

print(my_array)

[[1 2]
 [3 7]
 [4 5]
 [6 8]]


## Numpy Array Mathematics

In [28]:
n1 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

n2 = np.array([10,20,30])

n3 = np.array([
    [10,10,10],
    [20,20,20],
    [30,30,30]
])

n4 = np.array([30,20,10])

#### Addition
- To add two arrays, both should have same dimensions(rows x cols)
- We can add them as: `np.sum([arr1,arr2])`

In [32]:
## WILL THROW AN ERROR AS n2 has 1x3 dimension while n3 has 3x3
np.sum([n2,n3])

ValueError: could not broadcast input array from shape (3,3) into shape (3,)

In [35]:
## ADD EVERYTHING TO GIVE A SINGLE NUM
np.sum([n2,n4])

120

In [36]:
## ADDITION WITH RESPECT TO ROWS - axis=1
np.sum([n2,n4],axis=1)

array([60, 60])

In [37]:
## ADDITION WITH RESPECT TO COLUMNS - axis=0
np.sum([n2,n4],axis=0)

array([40, 40, 40])

In [39]:
## ADD EVERY NUMBER
np.sum([n1,n3])

225

In [40]:
## ROW WISE - axis = 1
np.sum([n1,n3],axis=1)

array([[12, 15, 18],
       [60, 60, 60]])

In [41]:
## COLUMN WISE - axis = 0
np.sum([n1,n3],axis=0)

array([[11, 12, 13],
       [24, 25, 26],
       [37, 38, 39]])

## Joining Arrays
- vstack()
- hstack()
- column_stack()
<hr>

##### NOTE: DON'T FORGET TO use () inside function to pass arrays.

In [42]:
n5 = np.array([10,20,30])
n6 = np.array([2,4,6])

In [47]:
## VERTICAL STACK
## JOIN ARRAYS ROW-WISE
np.vstack((n5,n6))

array([[10, 20, 30],
       [ 2,  4,  6]])

In [48]:
## HORIZONTAL STACK
## JOINING ARRAYS COLUMN-WISE
np.hstack((n5,n6))

array([10, 20, 30,  2,  4,  6])

In [46]:
## TAKE EVERY ROW AND MERGE AS COLUMN
np.column_stack((n5,n6))

array([[10,  2],
       [20,  4],
       [30,  6]])

In [49]:
n1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
n3

array([[10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [51]:
np.column_stack((n1,n3))

array([[ 1,  2,  3, 10, 10, 10],
       [ 4,  5,  6, 20, 20, 20],
       [ 7,  8,  9, 30, 30, 30]])